role_model_profiles:
  product_owner:
    model: openai_gpt5
  business_analyst:
    model: openai_gpt5
  ba_lead:
    model: openai_gpt5_mini
  solution_architect:
    model: openai_gpt5
  system_analyst:
    model: openai_gpt5_mini
  developer:
    model: openai_gpt5
  senior_developer:
    model: openai_gpt5
  security_reviewer:
    model: openai_gpt5_mini
  qa_engineer:
    model: openai_gpt5_mini
  plan_maker:
    model: openai_gpt5
  plan_critique_generator:
    model: openai_gpt5_mini
  plan_critique_comparator:
    model: openai_gpt5_mini
